string = "this is a string "
print("length of string:", len(string))
print("uppercase string:",string.upper())
print("lowercase string:",string.lower())
print("reverse string:",string[::-1])
print("replace 'is' with 'was' :",string.replace("is","was"))
print("split string into a list :",string.split())
print("string in a capitalized case:",string.capitalize())
print("finding the word :",string.find("this"))
print("check if a string is digit :",string.isdigit()) 